import {
    HomeContainer,
    HomeHeader,
    GroupsContainer,
    Group,
    GroupItem,
    GroupTitle,
    ResultsContainer,
    GroupResultContainer,
    GroupResultContainerTitle,
    GroupResultContainerItem,
    ResultsTitle,
} from "./styles";

import Logo from "../../assets/images/logo.png";

export default function Home(){
    return (
        <HomeContainer>
            <HomeHeader>
                <img src={Logo} alt="logo"/>
                <button>INICIAR FASE DE GRUPOS</button>
            </HomeHeader>
            <GroupsContainer>
                <Group>
                    <GroupTitle>GRUPO A</GroupTitle>
                    <GroupItem>Brasil</GroupItem>
                    <GroupItem>Argentina</GroupItem>
                    <GroupItem>Equador</GroupItem>
                    <GroupItem>Austrália</GroupItem>
                </Group>
                <Group>
                    <GroupTitle>GRUPO A</GroupTitle>
                    <GroupItem>Brasil</GroupItem>
                    <GroupItem>Argentina</GroupItem>
                    <GroupItem>Equador</GroupItem>
                    <GroupItem>Austrália</GroupItem>
                </Group>
                <Group>
                    <GroupTitle>GRUPO A</GroupTitle>
                    <GroupItem>Brasil</GroupItem>
                    <GroupItem>Argentina</GroupItem>
                    <GroupItem>Equador</GroupItem>
                    <GroupItem>Austrália</GroupItem>
                </Group>
                <Group>
                    <GroupTitle>GRUPO A</GroupTitle>
                    <GroupItem>Brasil</GroupItem>
                    <GroupItem>Argentina</GroupItem>
                    <GroupItem>Equador</GroupItem>
                    <GroupItem>Austrália</GroupItem>
                </Group>
                <Group>
                    <GroupTitle>GRUPO A</GroupTitle>
                    <GroupItem>Brasil</GroupItem>
                    <GroupItem>Argentina</GroupItem>
                    <GroupItem>Equador</GroupItem>
                    <GroupItem>Austrália</GroupItem>
                </Group>
                <Group>
                    <GroupTitle>GRUPO A</GroupTitle>
                    <GroupItem>Brasil</GroupItem>
                    <GroupItem>Argentina</GroupItem>
                    <GroupItem>Equador</GroupItem>
                    <GroupItem>Austrália</GroupItem>
                </Group>
                <Group>
                    <GroupTitle>GRUPO A</GroupTitle>
                    <GroupItem>Brasil</GroupItem>
                    <GroupItem>Argentina</GroupItem>
                    <GroupItem>Equador</GroupItem>
                    <GroupItem>Austrália</GroupItem>
                </Group>
                <Group>
                    <GroupTitle>GRUPO A</GroupTitle>
                    <GroupItem>Brasil</GroupItem>
                    <GroupItem>Argentina</GroupItem>
                    <GroupItem>Equador</GroupItem>
                    <GroupItem>Austrália</GroupItem>
                </Group>
            </GroupsContainer>
            <ResultsTitle>Resultados da fase de grupos</ResultsTitle>
            <ResultsContainer>
                <GroupResultContainer>
                    <GroupResultContainerTitle>GRUPO A</GroupResultContainerTitle>
                    <GroupResultContainerItem>
                            <p>Brasil</p>
                            <input></input>
                            <input></input>
                            <p>Argentina</p>
                    </GroupResultContainerItem>
                    <GroupResultContainerItem>
                            <p>USA</p>
                            <input></input>
                            <input></input>
                            <p>Soviética</p>
                    </GroupResultContainerItem>
                    <GroupResultContainerItem>
                            <p>asdfasdf</p>
                            <input></input>
                            <input></input>
                            <p>Brasil</p>
                    </GroupResultContainerItem>
                    <GroupResultContainerItem>
                            <p>Brasil</p>
                            <input></input>
                            <input></input>
                            <p>Brasil</p>
                    </GroupResultContainerItem>
                    <GroupResultContainerItem>
                            <p>Brasil</p>
                            <input></input>
                            <input></input>
                            <p>Brasil</p>
                    </GroupResultContainerItem>
                    <GroupResultContainerItem>
                            <p>Brasil</p>
                            <input value="2"></input>
                            <input></input>
                            <p>Brasil</p>
                    </GroupResultContainerItem>
                </GroupResultContainer>
                <GroupResultContainer>
                    <GroupResultContainerTitle>GRUPO A</GroupResultContainerTitle>
                    <GroupResultContainerItem>
                            <p>Brasil</p>
                            <input></input>
                            <input></input>
                            <p>Argentina</p>
                    </GroupResultContainerItem>
                    <GroupResultContainerItem>
                            <p>USA</p>
                            <input></input>
                            <input></input>
                            <p>Soviética</p>
                    </GroupResultContainerItem>
                    <GroupResultContainerItem>
                            <p>asdfasdf</p>
                            <input></input>
                            <input></input>
                            <p>Brasil</p>
                    </GroupResultContainerItem>
                    <GroupResultContainerItem>
                            <p>Brasil</p>
                            <input></input>
                            <input></input>
                            <p>Brasil</p>
                    </GroupResultContainerItem>
                    <GroupResultContainerItem>
                            <p>Brasil</p>
                            <input></input>
                            <input></input>
                            <p>Brasil</p>
                    </GroupResultContainerItem>
                    <GroupResultContainerItem>
                            <p>Brasil</p>
                            <input value="2"></input>
                            <input></input>
                            <p>Brasil</p>
                    </GroupResultContainerItem>
                </GroupResultContainer> 
                <GroupResultContainer>
                    <GroupResultContainerTitle>GRUPO A</GroupResultContainerTitle>
                    <GroupResultContainerItem>
                            <p>Brasil</p>
                            <input></input>
                            <input></input>
                            <p>Argentina</p>
                    </GroupResultContainerItem>
                    <GroupResultContainerItem>
                            <p>USA</p>
                            <input></input>
                            <input></input>
                            <p>Soviética</p>
                    </GroupResultContainerItem>
                    <GroupResultContainerItem>
                            <p>asdfasdf</p>
                            <input></input>
                            <input></input>
                            <p>Brasil</p>
                    </GroupResultContainerItem>
                    <GroupResultContainerItem>
                            <p>Brasil</p>
                            <input></input>
                            <input></input>
                            <p>Brasil</p>
                    </GroupResultContainerItem>
                    <GroupResultContainerItem>
                            <p>Brasil</p>
                            <input></input>
                            <input></input>
                            <p>Brasil</p>
                    </GroupResultContainerItem>
                    <GroupResultContainerItem>
                            <p>Brasil</p>
                            <input value="2"></input>
                            <input></input>
                            <p>Brasil</p>
                    </GroupResultContainerItem>
                </GroupResultContainer> 
                <GroupResultContainer>
                    <GroupResultContainerTitle>GRUPO A</GroupResultContainerTitle>
                    <GroupResultContainerItem>
                            <p>Brasil</p>
                            <input></input>
                            <input></input>
                            <p>Argentina</p>
                    </GroupResultContainerItem>
                    <GroupResultContainerItem>
                            <p>USA</p>
                            <input></input>
                            <input></input>
                            <p>Soviética</p>
                    </GroupResultContainerItem>
                    <GroupResultContainerItem>
                            <p>asdfasdf</p>
                            <input></input>
                            <input></input>
                            <p>Brasil</p>
                    </GroupResultContainerItem>
                    <GroupResultContainerItem>
                            <p>Brasil</p>
                            <input></input>
                            <input></input>
                            <p>Brasil</p>
                    </GroupResultContainerItem>
                    <GroupResultContainerItem>
                            <p>Brasil</p>
                            <input></input>
                            <input></input>
                            <p>Brasil</p>
                    </GroupResultContainerItem>
                    <GroupResultContainerItem>
                            <p>Brasil</p>
                            <input value="2"></input>
                            <input></input>
                            <p>Brasil</p>
                    </GroupResultContainerItem>
                </GroupResultContainer> 
                <GroupResultContainer>
                    <GroupResultContainerTitle>GRUPO A</GroupResultContainerTitle>
                    <GroupResultContainerItem>
                            <p>Brasil</p>
                            <input></input>
                            <input></input>
                            <p>Argentina</p>
                    </GroupResultContainerItem>
                    <GroupResultContainerItem>
                            <p>USA</p>
                            <input></input>
                            <input></input>
                            <p>Soviética</p>
                    </GroupResultContainerItem>
                    <GroupResultContainerItem>
                            <p>asdfasdf</p>
                            <input></input>
                            <input></input>
                            <p>Brasil</p>
                    </GroupResultContainerItem>
                    <GroupResultContainerItem>
                            <p>Brasil</p>
                            <input></input>
                            <input></input>
                            <p>Brasil</p>
                    </GroupResultContainerItem>
                    <GroupResultContainerItem>
                            <p>Brasil</p>
                            <input></input>
                            <input></input>
                            <p>Brasil</p>
                    </GroupResultContainerItem>
                    <GroupResultContainerItem>
                            <p>Brasil</p>
                            <input value="2"></input>
                            <input></input>
                            <p>Brasil</p>
                    </GroupResultContainerItem>
                </GroupResultContainer> 
                <GroupResultContainer>
                    <GroupResultContainerTitle>GRUPO A</GroupResultContainerTitle>
                    <GroupResultContainerItem>
                            <p>Brasil</p>
                            <input></input>
                            <input></input>
                            <p>Argentina</p>
                    </GroupResultContainerItem>
                    <GroupResultContainerItem>
                            <p>USA</p>
                            <input></input>
                            <input></input>
                            <p>Soviética</p>
                    </GroupResultContainerItem>
                    <GroupResultContainerItem>
                            <p>asdfasdf</p>
                            <input></input>
                            <input></input>
                            <p>Brasil</p>
                    </GroupResultContainerItem>
                    <GroupResultContainerItem>
                            <p>Brasil</p>
                            <input></input>
                            <input></input>
                            <p>Brasil</p>
                    </GroupResultContainerItem>
                    <GroupResultContainerItem>
                            <p>Brasil</p>
                            <input></input>
                            <input></input>
                            <p>Brasil</p>
                    </GroupResultContainerItem>
                    <GroupResultContainerItem>
                            <p>Brasil</p>
                            <input value="2"></input>
                            <input></input>
                            <p>Brasil</p>
                    </GroupResultContainerItem>
                </GroupResultContainer> 
                <GroupResultContainer>
                    <GroupResultContainerTitle>GRUPO A</GroupResultContainerTitle>
                    <GroupResultContainerItem>
                            <p>Brasil</p>
                            <input></input>
                            <input></input>
                            <p>Argentina</p>
                    </GroupResultContainerItem>
                    <GroupResultContainerItem>
                            <p>USA</p>
                            <input></input>
                            <input></input>
                            <p>Soviética</p>
                    </GroupResultContainerItem>
                    <GroupResultContainerItem>
                            <p>asdfasdf</p>
                            <input></input>
                            <input></input>
                            <p>Brasil</p>
                    </GroupResultContainerItem>
                    <GroupResultContainerItem>
                            <p>Brasil</p>
                            <input></input>
                            <input></input>
                            <p>Brasil</p>
                    </GroupResultContainerItem>
                    <GroupResultContainerItem>
                            <p>Brasil</p>
                            <input></input>
                            <input></input>
                            <p>Brasil</p>
                    </GroupResultContainerItem>
                    <GroupResultContainerItem>
                            <p>Brasil</p>
                            <input value="2"></input>
                            <input></input>
                            <p>Brasil</p>
                    </GroupResultContainerItem>
                </GroupResultContainer> 
                <GroupResultContainer>
                    <GroupResultContainerTitle>GRUPO A</GroupResultContainerTitle>
                    <GroupResultContainerItem>
                            <p>Brasil</p>
                            <input></input>
                            <input></input>
                            <p>Argentina</p>
                    </GroupResultContainerItem>
                    <GroupResultContainerItem>
                            <p>USA</p>
                            <input></input>
                            <input></input>
                            <p>Soviética</p>
                    </GroupResultContainerItem>
                    <GroupResultContainerItem>
                            <p>asdfasdf</p>
                            <input></input>
                            <input></input>
                            <p>Brasil</p>
                    </GroupResultContainerItem>
                    <GroupResultContainerItem>
                            <p>Brasil</p>
                            <input></input>
                            <input></input>
                            <p>Brasil</p>
                    </GroupResultContainerItem>
                    <GroupResultContainerItem>
                            <p>Brasil</p>
                            <input></input>
                            <input></input>
                            <p>Brasil</p>
                    </GroupResultContainerItem>
                    <GroupResultContainerItem>
                            <p>Brasil</p>
                            <input value="2"></input>
                            <input></input>
                            <p>Brasil</p>
                    </GroupResultContainerItem>
                </GroupResultContainer> 
            </ResultsContainer>
        </HomeContainer>
    );
}